[package]
name = "guessing_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Llamada a la libreria de funciones randomizadas
rand = "0.8.0"

